### ISSUE TITLE
Styles aren't being inlined

### ISSUE THREAD

**Issue by binlabs** [andrewrk/swig-email-templates#12]
I realize that this module relies on Juice to handle the inlining, but I figured there may be something about the implementation causing my troubles.

I should also note that this problem exists both when using the CLI and when using a script, and whether I write the output to my local FS or simply view it as stdout.

Everything seems to be working properly EXCEPT for inlining:
* Template inheritance works fine
* Generating dummy contexts works
* Including a context works

The style and link elements in my rendered templates are being stripped (as they should), but those stripped styles are never applied inline to the style attributes on my elements.

It doesn't matter whether I use very broad selectors, e.g.:
```
* {
  background-color: #ff0000;
}

html {
  font-family: Arial;
}
```

Or very specific selectors, e.g.:
```
#wrapperTable {
color: #333;
}
```

One last thing I'll mention is that the problem persisted whether I had this module installed globally or just locally to my project.

I'm running Windows 7 and haven't yet tried this module on my Ubuntu box - I hope to get to that within the next day.

In the meantime, any guidance or advice would be greatly appreciated.

**Comment by takkaria** [comment]
Closing this issue because it's been inactive for a long time.  Please re-open if this continues to be a problem.
