### ISSUE TITLE
Problem running on windows platform

### ISSUE THREAD

**Issue by alanosman** [andrewrk/swig-email-templates#28]
We are working with swig this week (it's a nice module) and testing on Windows and Mac.  On Mac it works fine, but on Windows there's an error with file path resolution both when running at the command line or in app code.  

When I traced out the issue, I found that changing line 31 of swig-email-templates/index.js so the "file://" is causing issues and removing it seems to clean up the error.

**var fileUrl = path.resolve(process.cwd(), path.join(options.root, templateName));**

I also realized that there is a command line error where the default folder for "templates" was not being applied when performing a readFileSync command in line 112 of swig-email-template.js

It should be:
**var str = fs.readFileSync(argv.r + "\\" + file, 'utf8');**

also need to strip out CRLF from argv which gets thrown in with a windows command line.

**Comment by takkaria** [comment]
Both of these should be fixed in 2.0.0.  Thanks
