### ISSUE TITLE
Package.js out of date

### ISSUE THREAD

**Issue by gsantome** [andrewrk/swig-email-templates#29]
Hello, I just update to node v12 and now I'm having an issue "error: uncaughtException: Module did not self-register" and I think is because the package.json inside swig-email-templates is really out of date. 

I'm trying to trace the error and I think is jsdom because you are using "jsdom": "~3.1.2", and they are in the version 5.

Thanks

**Comment by takkaria** [comment]
Hi, this is fixed now in version 2.0.0.  Thanks
