### ISSUE TITLE
Fix for Node version >= 4.x

### ISSUE THREAD

**Issue by michelem09** [andrewrk/swig-email-templates#30]
Please could you provide the fix for the newest version of node.js >= 4.x?
I can't neither install it, there are so many errors trying to compile the dependencies, fell free to contact me if you need info.
Many thanks

**Comment by amrdraz** [comment]
for me as far as I can tell it is failing because of the jsdom version this package is using

**Comment by michelem09** [comment]
Yes, I think it's that the problem, there is a really old version here, but trying to update it to the latest one it throws a lot of errors.

**Comment by takkaria** [comment]
Hi, I've published a fork that works with node 0.10+ based on this, https://www.npmjs.com/package/swig-email-templates-2 - hopefully temporarily until the original is fixed.

**Comment by andrewrk** [comment]
@takkaria would you like to take over the maintenance of this project?

**Comment by takkaria** [comment]
@andrewrk sure, do you want to email me about it at andi@takkaria.org?

**Comment by takkaria** [comment]
@michelem09 if you update to 2.0.0, this should be fixed. Thanks.

**Comment by michelem09** [comment]
I can confirm it. Thanks!
