### ISSUE TITLE
Should this work with nodemailer's embedded images using the 'cid' parameter?

### ISSUE THREAD

**Issue by Kopfy** [andrewrk/swig-email-templates#31]
emailHelper.templates.render('email_test.html', context, function (err, html, text) {
        emailHelper.transporter.sendMail({
            from: 'xy@gmail.com',
            to: 'yy@gmail.com',
            subject: 'Testmail',
            html: html,
            //text: text
            attachments: [{
                filename: 'logo.jpg',
                path: '../../public/img',
                cid: 'logouniquecid' //same cid value as in the html img src
            }]
        });
    });

Settings:
var templates = new EmailTemplates({
    root: global.appRoot + '/server/templates',
    text: false,            // Disable text alternatives
    swig: {
        cache: false        // Don't cache swig templates
    }
});

In email_test.html

`<img class="img-responsive" src="cid:logouniquecid"/>`

The cid value is the same as should be... however, I always get the rendered mail with inline CSS and the image, but I always get the following error:

Not found, skipping: cid:logouniquecid

**Comment by takkaria** [comment]
Hm, I agree that this shouldn't throw an error.  It's not this package that prints it, it's way up the stack in https://www.npmjs.com/package/web-resource-inliner.  For now you will have to put up with it, but I will see if there is a way to avoid this with patches upstream.

**Comment by Kopfy** [comment]
Hi!

Thank you!

Br,
    Marko

**Comment by halt-hammerzeit** [comment]
I wonder if `cid` is the way to go.
I read this article and it proposed three variants: CID, embedded base64 and CDN.
https://sendgrid.com/blog/embedding-images-emails-facts/
I tried `base64` but it simply said `Not found, skipping: data:image/png;base64,...`.
So apparently it parses `<img src/>` attribute and doesn't recognise the `data:` scheme.
I may try to use `CID` too.
(It's for a logo)

**Comment by takkaria** [comment]
web-resource-inliner won't touch URLs it doesn't understand, just throw a warning.  So if you use a data: url it won't remove it but it might say it doesn't understand it.

However, there's not much point in putting the image in a data: url yourself.  You might as well keep it separate on the filesystem for easier modification and let web-resource-inliner turn it into a data: URL for you.

**Comment by takkaria** [comment]
This has been fixed upstream (see https://github.com/jrit/web-resource-inliner/issues/21) so I will update dependencies soon and then this warning will be fixed.
