### ISSUE TITLE
Issue with cheerio encoding apostrophes

### ISSUE THREAD

**Issue by claygregory** [andrewrk/swig-email-templates#34]
Cheerio has a known issue with decoding then re-encoding apostrophes as `&apos;` which is not a valid HTML4 character entity. See cheeriojs/cheerio#319. Generally most browsers are pretty flexible… except for several versions of Outlook.

In the `render` function, using `cheerio.load(html, {decodeEntities: false});` would resolve this. Since Swig should already be returning valid HTML, no need to have cheerio altering character entities along the way.

**Comment by takkaria** [comment]
Thanks.  Will fix this week.
