### ISSUE TITLE
What about internationalization support?

### ISSUE THREAD

**Issue by halt-hammerzeit** [andrewrk/swig-email-templates#37]
I suggest you write a section in the Readme explaining your own "best practice" on internationalizing the emails being sent.

**Comment by takkaria** [comment]
I haven't tried to internationalise any code using this package, so I have no idea how that would work.  If you have a suggestion it would be happily accepted.

**Comment by halt-hammerzeit** [comment]
Since it would be correct to not duplicate styles and markup I guess the translation logic should be inside the `swig` template itself.
Like it gets a `locale` parameter and then inside that `.swig` file all strings are chosen (and formatted) according to that locale.

```
string message = if locale === 'en'
    "Bye"
else if locale === 'ru'
    "Русский"
end

{{ Helpers.formatCurrency(100000, locale) }}
```

I don't know if it's possible to inline javascript into `swig` like that.
If not then each string in the template can be passed explicitly like `.render(strings: { 'main.message': 'Я русский', 'main.balance': '0 шекелей' })`

**Comment by halt-hammerzeit** [comment]
I read Swig docs this week and immediately it was pointed out that one can freely use raw javascript functions for i18n.
So the solution is simple:

```html
{% extends "base.html" %}

{% block title %}
	{{ translate('mail.email_changed.title') }}
{% endblock %}

{% block css %}
	{% parent %}
	<link rel="stylesheet" href="email changed (old mailbox).css">
{% endblock %}

{% block content %}
	<p>
		{{ translate('mail.email_changed.old.email_changed_to', { email: '<strong>' + email + '</strong>' }, { escape: false }) }}.
	</p>

	<p>
		{{ translate('mail.email_changed.old.block_account', { block_account_link: '<a href="' + block_account_link + '">' + translate('mail.email_changed.old.block_account_link') + '</a>' }, { escape: false }) }}
	</p>
{% endblock %}
```

```js
{
	"mail.email_changed.title": "Your email has been changed",
	"mail.email_changed.old.email_changed_to": "Your email has been changed to {email}",
	"mail.email_changed.old.block_account_link": "block your account",
	"mail.email_changed.old.block_account": "In case that wasn't you then it can possibly mean that you're being hacked. In that case you can temporarily {block_account_link}.",
	"mail.email_changed.new.email_changed_to_this_mailbox": "Your email has been changed to this mailbox"
}
```

`translate()` function is passed to the rendering engine just like any other generic parameter. The first argument is the key inside the JSON file. The second argument are the parameters.
https://github.com/halt-hammerzeit/webapp/tree/master/backend/code/mail-service
