### ISSUE TITLE
Error: ENOENT: no such file or directory, open on up-gradation to latest version 

### ISSUE THREAD

**Issue by prasad47** [andrewrk/swig-email-templates#43]
Hi,

I updated recently to new version  "swig-email-templates": "5.0.1" and followed the code as per docs 

**Code to render html :-** 

```
var  emailTemplates = require('swig-email-templates'),
var templates = new emailTemplates();
var options = {
    root: path.join(__dirname, '../../templates') // need to add one more ../ to get precise path in project 
                                                                           screen shot added 
 };

 templates.render(options.root+'/email/mailchimp-order-confirm.html', order, function (err, html) {
        console.log('-------------** html ** ---------'+html);
        console.log('-------------------'+err);
        callback(html);
    });

 **Result error :-** 
** As per my Project structure the path which is saying not found is  Not True Pls take a look at the screen shot 

'-------------** html ** --------- undefined 
 -------------------Error: ENOENT: no such file or directory, open '/app/templates/email/mailchimp-order-confirm-interactive.html' 
```

Please Suggest !!

Thanks,
Prasad .

![error related screen](https://user-images.githubusercontent.com/6585745/37968507-f5b8b9ea-31eb-11e8-9e97-7e79a56a4932.png)

**Comment by takkaria** [comment]
I am not sure why you are concatenating `options.root` to the file path.  I assume when you call `templates.render()` the first parameter should just be `email/mailchimp-order-confirm.html`.

**Comment by prasad47** [comment]
if i did not concatenate in the` template.render()`  Server path is not being Precise .. it is generating error with Wrong path Like Following 
`-------------------Error: ENOENT: no such file or directory, open '/app/node_modules/swig-email-templates/templates/email/mailchimp-order-confirm-interactive.html' `
