### ISSUE TITLE
Dependency update - Minimist

### ISSUE THREAD

**Issue by hillct** [andrewrk/swig-email-templates#46]
I was thrilled to see the dependency updates that yielded the 6.0.0 release, as it made libe much more convenient, but one dependency was missed - that being Minimist which is at 1.2.5 as of 10 months ago. I wonder if we could see a 6.0.1 release with that dependency change,so we don't have to do obnoxious things to package-lock files to get swig-email-templates to play nice. Thanks.

**Comment by takkaria** [comment]
Hey, sorry, didn't see this.  We don't use minimist directly so it will require a bit more work to change the CLI to use either yargs or minimist itself.  Not sure when I'll have time to do it but if you want to submit a PR it will be merged quickly.
